# fly.toml app configuration file generated for helicone-mock-server on 2025-06-30T11:46:26-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'helicone-mock-server'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile.mock-server'
  ignorefile = '.dockerignore'

[[services]]
  protocol = 'tcp'
  internal_port = 5150
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  ports = []

[[vm]]
  memory = '4gb'
  cpu_kind = 'performance'
  cpus = 2
