// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
/*
 *  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *  SPDX-License-Identifier: Apache-2.0
 */

// use aws_smithy_http::event_stream::{InitialMessageType, Receiver};
// use aws_smithy_runtime_api::client::result::SdkError;
// use aws_smithy_types::event_stream::{Message, RawMessage};

#[derive(Debug)]
/// Receives unmarshalled events at a time out of an Event Stream.
pub struct EventReceiver<T, E> {
    inner: aws_smithy_http::event_stream::Receiver<T, E>,
}

impl<T, E> EventReceiver<T, E> {
    pub(crate) fn new(
        inner: aws_smithy_http::event_stream::Receiver<T, E>,
    ) -> Self {
        Self { inner }
    }
}
