// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
pub use crate::operation::converse_stream::_converse_stream_output::ConverseStreamOutput;

mod _converse_stream_output;
