// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(
    ::std::clone::Clone,
    ::std::cmp::PartialEq,
    ::std::fmt::Debug,
    serde::Deserialize,
)]
#[serde(rename_all = "camelCase")]
pub struct ConverseOutput {
    /// <p>The result from the call to <code>Converse</code>.</p>
    pub output: ::std::option::Option<crate::types::ConverseOutput>,
    /// <p>The reason why the model stopped generating output.</p>
    pub stop_reason: crate::types::StopReason,
    /// <p>The total number of tokens used in the call to
    /// <code>Converse</code>. The total includes the tokens input to the model
    /// and the tokens generated by the model.</p>
    pub usage: ::std::option::Option<crate::types::TokenUsage>,
    /// <p>Metrics for the call to <code>Converse</code>.</p>
    pub metrics: ::std::option::Option<crate::types::ConverseMetrics>,
    /// <p>Additional fields in the response that are unique to the model.</p>
    pub additional_model_response_fields:
        ::std::option::Option<aws_smithy_types::Document>,
    /// <p>A trace object that contains information about the Guardrail
    /// behavior.</p>
    pub trace: ::std::option::Option<crate::types::ConverseTrace>,
    /// <p>Model performance settings for the request.</p>
    pub performance_config:
        ::std::option::Option<crate::types::PerformanceConfiguration>,
    _request_id: Option<String>,
}
impl ConverseOutput {
    /// <p>The result from the call to <code>Converse</code>.</p>
    pub fn output(
        &self,
    ) -> ::std::option::Option<&crate::types::ConverseOutput> {
        self.output.as_ref()
    }
    /// <p>The reason why the model stopped generating output.</p>
    pub fn stop_reason(&self) -> &crate::types::StopReason {
        &self.stop_reason
    }
    /// <p>The total number of tokens used in the call to <code>Converse</code>.
    /// The total includes the tokens input to the model and the tokens
    /// generated by the model.</p>
    pub fn usage(&self) -> ::std::option::Option<&crate::types::TokenUsage> {
        self.usage.as_ref()
    }
    /// <p>Metrics for the call to <code>Converse</code>.</p>
    pub fn metrics(
        &self,
    ) -> ::std::option::Option<&crate::types::ConverseMetrics> {
        self.metrics.as_ref()
    }
    /// <p>Additional fields in the response that are unique to the model.</p>
    pub fn additional_model_response_fields(
        &self,
    ) -> ::std::option::Option<&aws_smithy_types::Document> {
        self.additional_model_response_fields.as_ref()
    }
    /// <p>A trace object that contains information about the Guardrail
    /// behavior.</p>
    pub fn trace(&self) -> ::std::option::Option<&crate::types::ConverseTrace> {
        self.trace.as_ref()
    }
    /// <p>Model performance settings for the request.</p>
    pub fn performance_config(
        &self,
    ) -> ::std::option::Option<&crate::types::PerformanceConfiguration> {
        self.performance_config.as_ref()
    }
}
