# fly.toml app configuration file generated for helicone-ai-gateway on 2025-06-30T11:50:14-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'helicone-ai-gateway'
primary_region = 'sjc'

[experimental]
  cmd = ['/usr/local/bin/ai-gateway', '-c', '/app/config/config.yaml']

[build]
  image = 'helicone/ai-gateway:latest'

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'

[[files]]
  guest_path = '/app/config/config.yaml'
  raw_value = '''

providers:
  openai:
    base-url: 'http://helicone-mock-server.internal:5150'
  anthropic:
    base-url: 'http://helicone-mock-server.internal:5150'
  gemini:
    base-url: 'http://helicone-mock-server.internal:5150'
  bedrock:
    base-url: 'http://helicone-mock-server.internal:5150'

minio:
  host: 'http://helicone-mock-server.internal:5150'

helicone:
  base-url: 'http://helicone-mock-server.internal:5150'
  websocket-url: 'ws://helicone-mock-server.internal:5150/ws/v1/router/control-plane'
  authentication: true
  observability: false

telemetry:
  level: info
  exporter: both
  otlp-endpoint: "http://helicone-otel-collector.internal:4317/v1/metrics"
'''

[[vm]]
  memory = '4gb'
  cpu_kind = 'performance'
  cpus = 2

[env]
OTEL_METRIC_EXPORT_INTERVAL = 10000