# We don't actually deploy this to fly.io 
# since they still offer free metrics


app = 'helicone-prometheus'
primary_region = 'sjc'

[experimental]
  cmd = ['--config.file=/etc/config.yaml', '--web.enable-remote-write-receiver', '--web.enable-otlp-receiver', '--enable-feature=exemplar-storage']

[build]
  image = 'prom/prometheus:v3.4.1'

[[services]]
  protocol = 'tcp'
  internal_port = 9090
  ports = []

[[files]]
  guest_path = '/etc/config.yaml'
  local_path = './config-production.yaml'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
