// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
#[allow(missing_docs)] // documentation missing in model
#[non_exhaustive]
#[derive(::std::fmt::Debug)]
pub struct ConverseStreamOutput {
    /// <p>The output stream that the model generated.</p>
    pub stream: crate::event_receiver::EventReceiver<crate::types::ConverseStreamOutput, crate::types::error::ConverseStreamOutputError>,
    _request_id: Option<String>,
}
impl ConverseStreamOutput {
    /// <p>The output stream that the model generated.</p>
    pub fn stream(
        &self,
    ) -> &crate::event_receiver::EventReceiver<crate::types::ConverseStreamOutput, crate::types::error::ConverseStreamOutputError> {
        &self.stream
    }
}