[package]
name = "mock-server"
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false
version.workspace = true
description = "A standalone binary for running a mock server for the AI Gateway 3rd party apis in order to enable load testing"

[dependencies]
ai-gateway = { workspace = true, features = ["testing"] }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
stubr = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
